
server:
  port : 8085

spring:
  datasource:
    url: jdbc:sqlserver://kindnesskattledb.chevdymucho3.eu-west-1.rds.amazonaws.com:1433;databaseName=dbkindkattle;encrypt=true;trustServerCertificate=true
    username: admin
    password: imkrsnna
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

